version: "3"
services:
  mongo:
    image: mongo:4.4.6
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
  localstack:
    image: localstack/localstack-full:latest
    environment:
      - AWS_DEFAULT_REGION=eu-west-1
      - EDGE_PORT=4566
#      - SERVICES=lambda,sqs
    ports:
      - 4566:4566
      - 4571:4571
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"